export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_PRODUCTS_DETAIL_BEGIN = "GET_PRODUCTS_DETAIL_BEGIN";
export const GET_PRODUCTS_DETAIL_SUCCESS = "GET_PRODUCTS_DETAIL_SUCCESS";
export const GET_PRODUCTS_DETAIL_ERROR = "GET_PRODUCTS_DETAIL_ERROR";
export const GET_STORED_FEATURED_PRODUCTS = "GET_STORED_FEATURED_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
